### PR TITLE
remove height restrictions

### PR DESCRIPTION
**Pull request by kevinawoo**
I've been testing this out on our 7x28 panels and it seems like it's good!

### CODE REVIEW

**Comment by caseymrm** [comment]
Oh, hah, forgot that check was in there. So glad it's working and useful!

What else would be useful? I was thinking about having another class that combined multiple panels into a larger virtual board, but I saw you're doing that outside this library, do you think that'd be worth it here?

**Comment by kevinawoo** [comment]
Yeah! I'm down to move some of my stuff into your library.

**Comment by kevinawoo** [comment]
Thinking about it, it might not be worth it because I'm noticing when I'm sending all 20 payloads, the flip times are a bit slower than I'd like. 
I'd prob end up buying another USB->RS485 controller and seeing if that would help improve speeds. (10 panels per usb instead of 20 per usb)

**Comment by caseymrm** [comment]
Interesting, is it noticeably faster or slower when you change the baud rate?

Also it's probably worth changing it to send the data to all 20, then doing one big refresh, I bet that's faster.

**Comment by kevinawoo** [comment]
I'll give the baud rate change a try. I just mounted all 10 panels
together, going to get it up to the wall and some other performance things
after

**Pull request merged**
